"""Generate the supplementary tables for Additional file 1.

Every table here is derived from the recompute JSONs, never typed by hand, for the same reason
build_tables.py exists: a hand-maintained supplementary drifts from the analysis silently and
nobody notices, because nobody reads the supplement until a referee does.

Writes reports/supplementary_tables.md, which build_supplementary_doc assembles into
reports/gb_supplementary.md together with the supplementary prose.

Usage:
    python src/ccs/build_supplementary.py
"""
import io
import json
import os

R = "reports/"


def J(name):
    return json.load(io.open(R + name + ".json", encoding="utf-8"))


def f(x, n=3, sign=False):
    if x is None:
        return "--"
    if isinstance(x, str):
        return x
    fmt = "%+." + str(n) + "f" if sign else "%." + str(n) + "f"
    return fmt % x


def ci(lo, hi, n=3):
    if lo is None or hi is None:
        return "--"
    return "[%s, %s]" % (f(lo, n, True), f(hi, n, True))


CAPTION_S28 = (
    "Table S28. In-sample likelihood ratios for the human arm at thresholds taken from the benign "
    "score distribution")

NOTE_S28 = (
    "No evidence-strength claim is made in this table: the likelihood ratios are computed "
    "in-sample, and the benign set they come from is not consequence-matched to the positives. "
    "Thresholds are set at quantiles of the benign score distribution and the false-positive rate "
    "is then read off that same set, so no held-out data enter. The benign set is 12,999 "
    "noncoding variants against 4,377 coding, and the positives are coding-dominated, so a "
    "threshold taken from it does not carry over to a missense variant. None of these ratios is "
    "an ACMG/AMP evidence assignment. LR+ is a ratio of within-class densities and does not "
    "depend on the class ratio in this panel. This is human-only of necessity: it needs an "
    "adjudicated benign set, which the eight label-poor species do not have, and no "
    "evidence-strength claim is made for them. It also comes from a threshold rule rather than a "
    "fitted local posterior, and the PP3 circularity discussed in the Discussion applies most "
    "sharply here, so we report it as a likelihood ratio and not as a calibrated evidence "
    "strength. The intervals are variant-level percentile bootstraps at a fixed threshold, with "
    "no gene clustering and no clustered sensitivity check. The top row rests on 18 benign "
    "variants above its threshold.")

TAIL_S28 = (
    "We do not map these ratios onto the ACMG/AMP evidence tiers. A mapping would need a held-out "
    "calibration set, thresholds set separately for each variant consequence, and local "
    "posteriors. This arm has none of the three, and the table is not intended for use in variant "
    "curation.")

def main():
    F4, F5, F3, F2, F6 = J("fig4_reconciliation"), J("fig5_reach"), J("fig3_data"), J("fig2_data"), J("fig6_free")
    F3S = J("fig3_stats")    # Table S9 intervals: see the note there on which bootstrap is canonical
    F4M = J("fig4_matrix")   # deposited operating-point trajectory + intervals
    T = J("tost_equivalence")
    out = []
    W = out.append

    W("# Supplementary Tables\n")
    W("*Generated by `src/ccs/build_supplementary.py` from the deposited recompute layers. "
      "Do not edit by hand.*\n")
    # regenerating this file reproduces its bracketed markers exactly, wrong
    # numbers included, because the numbering is a separate step (a separate renumbering step, not deposited)
    # and this is its INPUT. So the header has to be emitted here; written into the output it is
    # wiped by the next build, which is what happened to it once already.
    W("> **Citation scheme — read this before resolving any bracketed marker.** This file is a "
      "pre-renumbering **source**, not the reader-facing supplement. Its markers cite the 144-entry "
      "draft reference list; the submitted manuscript's list was trimmed to 86 and renumbered, so "
      "resolving a marker here against that list returns the wrong paper. The reader-facing "
      "supplement is **Additional file 1**, which is renumbered and correct. To resolve a marker "
      "here, go through `reports/supplementary_citation_map.json`, generated from the two lists by "
      "text matching and shipped in this deposit.\n")

    # ---------------- S1 atlas ----------------
    W("\n## Table S1. The readout effect on identical variants\n")
    # This preamble used to name specific residuals against Table 1: sheep "matching exactly at
    # 0.902", horse "0.882 here against 0.880 in Table 1", and five species losing 21 variants
    # between them. Every one of those figures was hardcoded, and every one had been superseded.
    # Table 1 is now built from this same panel, so the two agree for all nine species at identical
    # n, and sheep reads 0.903 in both. The agreement is COUNTED here rather than asserted, so it
    # cannot go stale the way a hardcoded residual list did.
    _n_sp = len(F2["forest"])
    _have = sum(1 for r in F2["forest"] if r.get("auroc_1001") is not None)
    assert _have == _n_sp, ("Table S1 lacks a 1,001-bp value for %d of %d species, so the claim "
                            "that it reproduces Table 1 exactly would be false as written."
                            % (_n_sp - _have, _n_sp))
    W("Both columns are computed on the **same variants**, every variant carrying an 8,192-bp "
      "mean-log-likelihood score, %s of the 11,130 in the panel, so the two readouts are matched "
      "variant-for-variant and isolate the readout effect: %s AUROC by the species mean, %s pooled "
      "%s. Before the 8,192-bp panel was completed these columns covered only 3,506 variants, and "
      "the 1,001-bp values here differed materially from those in Table 1. "
      # The caption used to assert "identical n for all 9" and "reproduces Table 1's exactly". Its
      # own first sentence refutes that: Table 1 is the full 11,130-variant panel and this table the
      # 11,109 carrying an 8,192-bp score. Five species lose a variant at a contig end and three of
      # them move at three decimals. Claiming a match the n column disproves is the exact failure
      # this paper is about, so the residual is now named instead of denied.
      "Table 1 is computed on the full 11,130-variant panel and this table on the %s carrying an "
      "8,192-bp score, so n differs in the five species that lose a variant at a contig end "
      "(horse 15, cat 3, and one each in goat, cattle and dog; Note S38), and the 1,001-bp AUROC "
      "shifts with it at three decimals in goat, horse and cat. That panel difference is the whole "
      "of the residual, and the readout effect above is computed on the matched subset.\n"
      % (f"{F2['readout_pooled']['n']:,}",
         f(F2["readout_macro"]["delta"], 3, True),
         f(F2["readout_pooled"]["delta"], 3, True),
         ci(F2["readout_pooled"]["ci"][0], F2["readout_pooled"]["ci"][1]),
         f"{F2['readout_pooled']['n']:,}"))
    W("| Species | n | AUROC 8,192-bp mean-LL | 95% CI | AUROC 1,001-bp single-pos (same variants) |")
    W("|---|--:|--:|:--|--:|")
    for r in F2["forest"]:
        sp = r["species"]
        W("| %s | %s | %s | %s | %s |" % (
            sp.capitalize(), r.get("n", "--"), f(r.get("auroc")),
            ci(r.get("lo"), r.get("hi")), f(r.get("auroc_1001"))))

    # ---------------- S2 ECE estimator sweep ----------------
    W("\n## Table S2. Expected calibration error is estimator-dependent\n")
    nr = F4["null_robustness"]
    W("Macro-averaged ECE for the transferred isotonic map, the trivial two-parameter global "
      "sigmoid, and an in-species oracle, across twelve binning rules. The formal paired test was "
      "run on four of these (`ece_grid`): **%d of %d are indistinguishable**, with %s dissenting in "
      "transfer's favour. We report the disagreement rather than a majority verdict.\n"
      % (nr["n_indistinguishable"], nr["n_macro_estimators"],
         ", ".join(nr["dissenting"].keys()) or "none"))
    W("| Binning rule | isotonic (transfer) | trivial sigmoid | in-species oracle | isotonic - sigmoid |")
    W("|---|--:|--:|--:|--:|")
    for k, v in F4["bin_sweep_macro"].items():
        d = v["isotonic_LOSO"] - v["trivial_sigmoid_LOSO"]
        W("| %s | %s | %s | %s | %s |" % (k, f(v["isotonic_LOSO"], 4), f(v["trivial_sigmoid_LOSO"], 4),
                                          f(v["oracle_isotonic"], 4), f(d, 4, True)))
    eb = nr.get("effective_bins", {})
    if eb:
        W("\n**Why equal-mass rules disagree with equal-width rules.** The transferred isotonic "
          "posterior takes only a few dozen distinct values per species, so an equal-mass rule "
          "cannot deliver the bin count it is asked for. Requested versus achieved:\n")
        W("| Species | mass10 -> effective | mass15 -> effective |")
        W("|---|--:|--:|")
        for sp, v in eb.items():
            W("| %s | %d | %d |" % (sp.capitalize(), v.get("mass10", 0), v.get("mass15", 0)))
        # Note S2 supersedes the degeneracy explanation for the SIGN disagreement; this caption used
        # to assert the opposite of the note it sits beside.
        W("\nThis degeneracy is real, but it is **not** the source of the sign disagreement above: "
          "under equal-mass rules the isotonic advantage over the trivial sigmoid strengthens "
          "monotonically as the requested bin count rises, which a binning degeneracy would not "
          "produce. See Note S2, which supersedes the degeneracy explanation.")

    # P16: the formal test was run on four estimators x two aggregations = eight cells; report all
    # eight, not only the four macro cells. The two pooled cells are significant in OPPOSITE
    # directions, which is itself the evidence that pooled ECE is unstable here.
    eg = F4.get("ece_grid", {})
    if eg:
        W("\n**Both aggregations of the four formally tested estimators (eight cells).** The paired "
          "test was run on equal-width and equal-mass binning at 10 and 15 bins, under macro and "
          "pooled aggregation. We report all eight rather than only the macro four. The two pooled "
          "cells disagree in sign (width10 favours transfer, width15 favours the sigmoid) which is "
          "the direct evidence that pooled ECE is unstable on this posterior and why the macro "
          "aggregation is used in the main text.\n")
        W("| Estimator | aggregation | isotonic (transfer) | trivial sigmoid | isotonic - sigmoid |")
        W("|---|---|--:|--:|--:|")
        for rule in ["width10", "width15", "mass10", "mass15"]:
            cell = eg.get(rule, {})
            iso, sig = cell.get("isotonic_LOSO", {}), cell.get("trivial_sigmoid_LOSO", {})
            for agg in ["macro", "pooled"]:
                if agg in iso and agg in sig:
                    W("| %s | %s | %s | %s | %s |" % (
                        rule, agg, f(iso[agg], 4), f(sig[agg], 4), f(iso[agg] - sig[agg], 4, True)))

    # ---------------- S3 calibration per species ----------------
    W("\n## Table S3. Calibration transfer per species, leave-one-species-out\n")
    g = F4["ece_grid"]["width10"]
    arms = [("isotonic_LOSO", "transferred isotonic"),
            ("platt_LOSO", "transferred Platt"),
            ("trivial_sigmoid_LOSO", "trivial global sigmoid"),
            ("oracle_isotonic", "in-species oracle")]
    have = [(k, lab) for k, lab in arms if k in g and "per_species" in g[k]]
    if have:
        species = list(g[have[0][0]]["per_species"].keys())
        W("Equal-width 10-bin ECE. The transferred Platt map and the trivial global sigmoid are "
          "arithmetically the same operation and are bit-identical here, which is why the "
          "substantive comparison in the main text is isotonic against that sigmoid.\n")
        W("| Species | " + " | ".join(lab for _, lab in have) + " |")
        W("|---|" + "--:|" * len(have))
        for sp in species:
            W("| %s | %s |" % (sp.capitalize(),
                               " | ".join(f(g[k]["per_species"].get(sp), 4) for k, _ in have)))
        W("| **macro** | %s |" % " | ".join("**%s**" % f(g[k].get("macro"), 4) for k, _ in have))
        W("| **pooled** | %s |" % " | ".join(f(g[k].get("pooled"), 4) for k, _ in have))
    sc = F4.get("size_curve", {})
    if sc:
        W("\n**Calibration-set-size learning curve.** This is how much data the map is fitted on, "
          "in VARIANTS, not the number of donor species. It answers whether the smallest panels "
          "(goat, n = 99) are overfitting: they are not, and equally, more calibration data does "
          "not close the gap to the in-species oracle.\n")
        W("| calibration set size (variants) | mean transferred adaptive ECE | sd |")
        W("|---|--:|--:|")
        for i, n in enumerate(sc["n"]):
            W("| %s | %s | %s |" % (n, f(sc["mean_transfer_aece"][i], 4), f(sc["sd"][i], 4)))
        W("\nFlat within noise: **%s**." % sc.get("flat_within_noise"))

    # ---------------- S4 prior shift ----------------
    ps = F4.get("prior_shift", {})
    if ps and "sp" in ps:
        W("\n## Table S4. Prevalence correction to the panel construction ratio\n")
        # Note S4 retracts the phrase "deployment prevalence": the target column is the panel's own
        # 10:1 build ratio (0.091 = 1/11), and no screening decision is made at that prevalence.
        W("Calibrated probabilities were mapped from the donor-pool prevalence to the held-out "
          "panel's own construction ratio by Elkan-Saerens prior correction. The target is that "
          "build ratio, not a deployment prevalence; see Note S4.\n")
        W("| Species | n | positives | prevalence (source) | prevalence (target) | ECE uncorrected | ECE corrected |")
        W("|---|--:|--:|--:|--:|--:|--:|")
        for i, sp in enumerate(ps["sp"]):
            W("| %s | %s | %s | %s | %s | %s | %s |" % (
                sp.capitalize(), ps["n"][i], ps["pos"][i], f(ps["pi_src"][i]), f(ps["pi_tgt"][i]),
                f(ps["ece_uncorr"][i]), f(ps["ece_corr"][i])))

    # ---------------- S5 conformal ----------------
    cf = F4.get("conformal", {})
    if cf and "sp" in cf:
        W("\n## Table S5. Mondrian versus marginal conformal prediction\n")
        W("The marginal construction abstains far less but lets **positive-class** coverage "
          "collapse, on exactly the variants a clinician most needs to catch. This is why every "
          "conformal claim in the main text is the Mondrian (class-conditional) arm.\n")
        W("| Species | n | pos | Mondrian cov. | Mondrian cov. (pos.) | Mondrian abstain | "
          "marginal cov. | marginal cov. (pos.) | marginal abstain |")
        W("|---|--:|--:|--:|--:|--:|--:|--:|--:|")
        for i, sp in enumerate(cf["sp"]):
            W("| %s | %s | %s | %s | %s | %s | %s | %s | %s |" % (
                sp.capitalize(), cf["n"][i], cf["pos"][i],
                f(cf["cov_mond"][i]), f(cf["cov_path"][i]), f(cf["abstain"][i]),
                f(cf["cov_marg"][i]), f(cf["cov_path_marg"][i]), f(cf["abstain_marg"][i])))

    # ---------------- S6 risk-coverage ----------------
    ab = F4.get("abstention", {}).get("isotonic_LOSO", {})
    if ab:
        W("\n## Table S6. Selective prediction: the risk-coverage curve\n")
        cen = F4.get("staircase", {}).get("census", {})
        if cen:
            # Two different schemes, with different counts: applying a 15% threshold
            # WITHIN each species refuses 1,673 calls, a realised 15.03%, because each species'
            # count is rounded; a single global 15% cut refuses 1,669. The per-species capture
            # (316 of 893) therefore divides by 1,673, giving lift 2.35 rather than 2.36.
            n_ref = sum(v["n_refused"] for v in F4.get("staircase", {}).get("per_species", {}).values())
            # The lift is derived from the same two `cen` fractions that fill the rest of this
            # sentence, so it cannot drift away from the capture and refusal figures printed
            # beside it; 2.35 is the fallback for the case where either fraction is absent.
            _fc, _fr = cen.get("frac_errors_captured"), cen.get("frac_refused")
            _lift = (_fc / _fr) if (_fc and _fr) else 2.35
            W("Refusing each species' own least-confident 15%% of calls defers %s of 11,130 "
              "(a realised %.2f%%, the threshold being applied within each species) and captures "
              "**%.1f%%** of all errors (%d of %d), a lift of %.2f over refusing at random. "
              "Refusing the worst 15%% globally instead, ignoring species, defers 1,669 calls and "
              "captures 38.4%% (343), lift 2.56.\n"
              % (format(n_ref, ","), 100 * cen.get("frac_refused", 0.1503),
                 100 * cen.get("frac_errors_captured", 0),
                 cen.get("errors_captured", 0), cen.get("n_errors", 0), _lift))
        W("| Coverage | macro selective error | random-refusal control | pooled selective error |")
        W("|---|--:|--:|--:|")
        # The random-refusal control is abstention.isotonic_LOSO.macro_random -- the error when the
        # SAME fraction of calls is refused at random. It must stay flat (~0.057) as coverage falls;
        # that flatness is the evidence the selective predictor is doing real work. A previous version
        # of this table printed trivial_sigmoid_LOSO.macro_error here, which is the sigmoid
        # calibrator's OWN selective curve (it declines), making the table contradict the main text.
        rnd = ab.get("macro_random", [])
        for i, c in enumerate(ab["coverage"]):
            W("| %.0f%% | %s | %s | %s |" % (
                100 * c, f(ab["macro_error"][i], 4),
                f(rnd[i], 4) if i < len(rnd) else "--",
                f(ab["pooled_error"][i], 4)))
        W("\nThe minimum sits at 85% coverage; refusing beyond it buys nothing and eventually costs, "
          "as the retained set becomes small and unrepresentative.")
        # Deployed (Platt) arm to 20% coverage, with the retained-set sensitivity. The macro column above bumps and recovers; the pooled/deployed error rises
        # monotonically below 85% and crosses the do-nothing baseline, while sensitivity collapses.
        traj = F4M.get("_meta", {}).get("trajectory", [])
        base = next((r["error"] for r in traj if r["coverage"] == 1.0), None)
        if traj and base is not None:
            W("\n**The deployed (Platt) arm, full trajectory to 20%% coverage.** The table above uses "
              "the isotonic arm and stops at 30%%; the per-variant deliverable is the Platt arm "
              "(Methods), whose deposited trajectory runs to 20%% and reports the retained-set "
              "sensitivity. Its error rises monotonically below the 80-85%% minimum and crosses the "
              "do-nothing baseline of %.4f, so below that crossing the layer is worse than answering "
              "every variant; sensitivity collapses in step while specificity climbs toward 1.0, "
              "pushed hard, the layer answers 'benign' to almost everything (`reports/fig4_matrix.json`).\n"
              % base)
            W("| Coverage | n kept | pooled error | vs do-nothing | sensitivity | specificity |")
            W("|---|--:|--:|:--|--:|--:|")
            for r in traj:
                flag = "worse" if r["error"] > base + 1e-9 else ("baseline" if r["coverage"] == 1.0 else "better")
                W("| %.0f%% | %s | %s | %s | %s | %s |" % (
                    100 * r["coverage"], format(r["n_kept"], ","), f(r["error"], 4), flag,
                    f(r["sensitivity"], 3), f(r["specificity"], 3)))

    # ---------------- S7 reach ----------------
    W("\n## Table S7. Reach: what the conservation baseline can be run on\n")
    W("Conservation scores are undefined where the alignment fails, and the failure is "
      "class-dependent. Every per-species conservation AUROC computed this way is therefore "
      "computed on a subset easier than the panel it is drawn from; we establish that within our "
      "own nine panels and do not survey the published literature. The missingness is also "
      "spatially structured rather than random: a Wald-Wolfowitz runs test on the deposited "
      "tracks rejects randomly scattered no-calls in the three largest panels (human z = -13.87 "
      "benign and -13.94 pathogenic, dog -10.86, cattle -7.31; `reports/fig5_reach.json`, "
      "`src/ccs/fig5_stats.py`). That cuts both ways: it is independent evidence that the holes "
      "are structural, and it means the per-variant reach intervals below assume an independence "
      "of missingness that the runs test rejects, so they understate uncertainty in exactly those "
      "three panels.\n")
    W("| Species | n | positive scorable | negative scorable | class gap | deployment AUROC penalty |")
    W("|---|--:|--:|--:|--:|--:|")
    for r in F5["per_species"]:
        W("| %s | %s | %s | %s | %s | %s |" % (
            r["species"].capitalize(), r.get("n", "--"),
            f(r.get("reach_pos")), f(r.get("reach_neg")),
            f(r.get("class_gap"), 3, True), f(-r.get("must_call_penalty", 0), 3, True)))

    # ---------------- S8 baselines ----------------
    W("\n## Table S8. Baseline suite\n")
    sup = F5.get("supervised", {}).get("rows", [])
    if sup:
        W("**Supervised models trained on the labels themselves.** The n column is the panel each baseline was trained and evaluated on, which for four species is marginally smaller than the full panel in Table 1 (horse 766 against 781, cat 1,362 against 1,365, cattle 2,067 against 2,068, dog 2,496 against 2,497), because a baseline needs a window every model can score. The Evo 2 column is computed on this same reduced set, not carried over from Table 1, so the comparison is like-for-like. Point estimates only: the "
          "baseline scripts retain no per-variant predictions, so paired intervals are not "
          "computable from the deposited files.\n")
        W("| Species | n | 1D-CNN | k-mer | Evo 2-40B (zero-shot) | CNN leave-one-species-out |")
        W("|---|--:|--:|--:|--:|--:|")
        for r in sup:
            W("| %s | %s | %s | %s | %s | %s |" % (
                r["species"].capitalize(), r["n"], f(r.get("auroc_cnn")), f(r.get("auroc_kmer")),
                f(r.get("auroc_evo2")), f(r.get("cnn_loso"))))
    plm = F5.get("protein_lm", {})
    if plm:
        # The single n column did not apply to the GERP cell. ESM-2 and Evo 2 are measured on all n
        # variants; GERP is measured only on the subset it can score -- 881 of 912 in human -- which
        # is the same selection artefact this figure exists to indict, applied by the table to its own
        # comparison. GERP now carries its own n, and the abstention value from the recompute layer is
        # shown beside the covered one so the reader can see what the missing variants cost.
        W("\n**Protein language model**, runnable on only the panels with annotated missense variants.\n")
        W("| Species | n | n pos | ESM-2 | Evo 2-40B | GERP (n scoreable) | GERP covered | "
          "GERP must-answer |")
        W("|---|--:|--:|--:|--:|--:|--:|--:|")
        for sp, r in plm.items():
            if isinstance(r, dict) and "auroc_esm" in r:
                W("| %s | %s | %s | %s | %s | %s | %s | %s |" % (
                    sp.capitalize(), r.get("n"), r.get("n_pos"), f(r.get("auroc_esm")),
                    f(r.get("auroc_evo2")), r.get("n_gerp_scoreable", "--"),
                    f(r.get("auroc_gerp")), f(r.get("auroc_gerp_abstain"))))
        W("\n*The n column applies to ESM-2 and Evo 2-40B. GERP is measured on the subset it can "
          "score, given separately; its must-answer column charges it for the rest at chance, the "
          "same accounting used in Figure 4.*\n")

    # ---------------- S9 scale ladder + peer scorers ----------------
    W("\n## Table S9. Scale does not close the regulatory gap\n")
    A = F3["A_scale_ladder"]
    # Estimates come from fig3_stats.json, not fig3_data.json. Both recompute the same quantities,
    # but fig3_data.py bootstraps the whole vector from a module-level RNG (so class counts wander
    # between resamples and the result depends on call order), while fig3_stats.py resamples
    # positives and negatives separately from a per-call seed. The stratified one is what the
    # Methods describe and what the manuscript quotes. They disagreed by 0.001 on the 40B lower
    # bound, so this table printed [+0.472, +0.523] against the text's [0.473, 0.523] in four
    # places. Row set and order still follow fig3_data so the table's content is unchanged.
    SC = F3S["scale"]["eqtl"]
    W("| Model | whole-atlas macro AUROC (n = 11,109) | eQTL AUROC | 95% CI | n (eQTL) |")
    W("|---|--:|--:|:--|--:|")
    for row in A["eqtl"]:
        st = SC[row["model"]]
        W("| Evo 2-%s | %s | %s | %s | %s |" % (
            row["model"], f(A["coding"].get(row["model"])), f(st["auroc"]),
            ci(st["lo"], st["hi"]), st["n_pos"] + st["n_neg"]))
    W("\nCoding discrimination rises monotonically across a 40-fold parameter range; eQTL "
      "discrimination does not move.\n")
    W("\n**Every sequence-based scorer collapses together on the same panel.** GERP is shown as one "
      "row per flavour because its reach on this panel is flavour-dependent (n varies with how many "
      "variants carry a finite score); each row is a genuine estimator with its own bootstrap "
      "interval, in place of an uninterpretable average across flavours.\n")
    W("| Scorer | AUROC | 95% CI | n |")
    W("|---|--:|:--|--:|")
    SS = F3S["scorers"]                      # same stratified estimator as the ladder above
    for row in F3["B_class_level"]["eqtl"]:
        if row["scorer"] == "GERP" and row.get("flavors"):
            for fl in row["flavors"]:
                st = SS["GERP:%s" % fl["flavor"]]
                W("| GERP (%s) | %s | %s | %s |" % (
                    fl["flavor"].replace("gerp_", ""), f(st["auroc"]),
                    ci(st["lo"], st["hi"]), st["n_pos"] + st["n_neg"]))
        else:
            st = SS[row["scorer"]]
            W("| %s | %s | %s | %s |" % (row["scorer"], f(st["auroc"]),
                                         ci(st["lo"], st["hi"]), st["n_pos"] + st["n_neg"]))

    # ---------------- S10 TOST ----------------
    W("\n## Table S10. Equivalence testing, Evo 2 versus GERP on the co-scorable panel\n")
    W("Observed difference %s on n = %d over %d species. The unit of analysis decides the "
      "answer, and we report the species-clustered interval because species are this study's "
      "unit of generalisation.\n" % (f(T["delta"], 4, True), T["n"], T["n_species"]))
    W("| Bootstrap | 90% CI | verdict at SESOI 0.02 |")
    W("|---|:--|---|")
    W("| species-clustered (reported) | %s | %s |" % (
        ci(T["ci90"][0], T["ci90"][1], 4),
        "equivalence NOT established" if not T["tost"]["delta_0.02"]["equivalent"] else "equivalent"))
    W("| variant-level (contrast only) | %s | %s |" % (
        ci(T["ci90_variant_level_for_contrast_only"][0], T["ci90_variant_level_for_contrast_only"][1], 4),
        "equivalent" if T["variant_level_equivalent_at_sesoi"] else "not equivalent"))
    W("\n| SESOI | p (TOST) | equivalent? |")
    W("|---|--:|---|")
    for k, v in T["tost"].items():
        W("| %s | %s | %s |" % (f(v["sesoi"], 2), f(v["p_tost"], 4), "yes" if v["equivalent"] else "no"))

    # ---------------- S11 label-free ----------------
    W("\n## Table S11. Label-free validation against the site-frequency spectrum\n")
    sel = F6.get("selection", {})
    if isinstance(sel, dict) and sel.get("bins"):
        sci = sel.get("spearman_ci", [None, None])
        W("**Cattle (%s), %s variants.** Mean predicted deleteriousness by minor-allele-frequency "
          "bin; Spearman rho = %s %s, p = %.3g. The claim is the monotone gradient at this n, not "
          "the magnitude of rho.\n"
          % (sel.get("build", "ARS-UCD1.2"), format(sel.get("n", 0), ","),
             f(sel.get("spearman_rho"), 3, True), ci(sci[0], sci[1], 3),
             sel.get("spearman_p", float("nan"))))
        W("| MAF bin | n | mean MAF | mean deleteriousness |")
        W("|---|--:|--:|--:|")
        # The main text retracted "singleton" for the lowest bin: at the 14,788 alleles observed a
        # true singleton sits near 6.8e-5, while this bin admits anything below 0.002. The retraction
        # never reached the recompute layer, whose key is still the original label, so it is renamed
        # at the point of printing rather than by editing the deposited artifact.
        RENAME = {"singleton": "ultra-rare"}
        for b in sel["bins"]:
            W("| %s | %s | %s | %s |" % (RENAME.get(b["freq_bin"], b["freq_bin"]),
                                         format(b["n"], ","),
                                         f(b["mean_maf"], 5), f(b["mean_del"], 3)))
        fc = sel.get("fold_change_extreme_bins")
        if fc:
            W("\nFold change, major-allele bin to ultra-rare bin: **%s**." % f(fc, 2))
    cond = F6.get("selection_conditioned", {})
    if isinstance(cond, dict) and cond.get("strata"):
        W("\n**Conditioned on conservation (phyloP quintiles).** The frequency-deleteriousness "
          "relationship survives at fixed conservation in 4 of 5 quintiles, and its interval "
          "crosses zero exactly where conservation itself has no signal, the regulatory blind "
          "spot, recovered with no disease label anywhere in the analysis.\n")
        W("| phyloP quintile | phyloP range | n | Spearman rho | 95% CI | p |")
        W("|---|---|--:|--:|:--|--:|")
        for q in cond["strata"]:
            c = q.get("ci") or [None, None]
            W("| %s | %s to %s | %s | %s | %s | %s |" % (
                q["stratum"] + 1, f(q["phylop_lo"], 2), f(q["phylop_hi"], 2), format(q["n"], ","),
                f(q["rho"], 3, True), ci(c[0], c[1], 3),
                ("%.3g" % q["p"]) if q.get("p") is not None else "--"))
        W("\nStrata with negative rho: **%s of %s**; strata whose CI excludes zero: **%s**."
          % (cond.get("n_strata_rho_negative"), len(cond["strata"]),
             cond.get("n_strata_ci_excludes_zero")))

    # ---------------- S12 readout head-to-head ----------------
    hh_path = R + "readout_headtohead.json"
    if os.path.exists(hh_path):
        H = json.load(io.open(hh_path, encoding="utf-8"))
        W("\n## Table S12. Evo 2 versus GERP is readout-dependent (co-scorable variants)\n")
        # The GERP column here is restricted to variants that ALSO carry an 8,192-bp score, so it
        # differs slightly from Table 1's GERP column, which uses every finite-GERP variant. For cat
        # the two sets are 1,034 and 1,037 variants and the AUROCs are 0.8565 and 0.8460: three
        # variants move it by 0.0105. The two can be read as contradicting each other,
        # so the difference is now stated rather than left for a reader to reconcile.
        W("On the variants both methods can score, Evo 2 scored at the 1,001-bp single-position "
          "readout and at the 8,192-bp mean-log-likelihood readout, against the same fixed GERP "
          "baseline, per species. Moving Evo 2 from the single-position to the mean-log-likelihood "
          "readout raises its macro margin over GERP from %s (leading %d of %d species) to %s "
          "(9 of 9), while GERP is unchanged, so the near-parity at the single-position readout is "
          "an artifact of the readout, not the panel. **The GERP column here is restricted to "
          "variants that also carry an 8,192-bp score, so it differs slightly from the GERP column "
          "of Table 1, which uses every variant GERP can score**; for cat the two sets are 1,034 "
          "and 1,037 variants and GERP reads 0.856 against 0.846. Paired species-clustered bootstrap on the "
          "8,192-bp difference: macro %s, 95%% CI %s.\n"
          % (f(H["macro_evo2_1001_same_variants"] - H["macro_gerp"], 3, True),
             H["n_evo2_leads_1001_same_variants"], H["n_species"],
             f(H["macro_evo2_8192"] - H["macro_gerp"], 3, True),
             f(H["macro_delta"], 3, True),
             ci(H["macro_delta_ci95"][0], H["macro_delta_ci95"][1], 3)))
        W("| Species | n (co-scorable) | Evo 2 @1,001-bp | Evo 2 @8,192-bp | GERP | Δ (8,192 − GERP) |")
        W("|---|--:|--:|--:|--:|--:|")
        for sp, p in H["per_species"].items():
            W("| %s | %s | %s | %s | %s | %s |" % (
                sp.capitalize(), p["n"], f(p.get("auroc_evo2_1001_same_variants")),
                f(p["auroc_evo2_8192"]), f(p["auroc_gerp"]), f(p["delta"], 3, True)))
        W("| **macro** | | %s | %s | %s | %s |" % (
            f(H["macro_evo2_1001_same_variants"]), f(H["macro_evo2_8192"]),
            f(H["macro_gerp"]), f(H["macro_delta"], 3, True)))

    # ---------------- S13 phyloP cross-check ----------------
    pc_path = R + "phylop_crosscheck.json"
    if os.path.exists(pc_path):
        PC = json.load(io.open(pc_path, encoding="utf-8"))["per_species"]
        rows = [(sp, PC[sp]) for sp in ("cattle", "chicken", "human")
                if sp in PC and "auroc_phylop" in PC[sp]]
        if rows:
            W("\n## Table S13. phyloP versus GERP where a phyloP track is available\n")
            W("GERP is the sole cross-species conservation baseline because it is the only per-base "
              "score available for all nine assemblies (Methods). For chicken (galGal6/GRCg6a UCSC "
              "phyloP77way) and human (hg38/GRCh38 UCSC phyloP100way), which carry a genuine UCSC "
              # Not project-computed and not undocumented. conf/DATA_SOURCES.md records it as a
              # Zenodo download over a documented Cactus 241-way alignment, and query_phylop.py says
              # so in its docstring. Claiming otherwise was a provenance falsehood in a paper whose
              # subject is provenance. The real caveat is the different alignment, which stays.
              "phyloP track, and cattle (bosTau9), whose phyloP comes from Zenodo record 13332541 "
              "(Roslin) over a Cactus 241-way alignment rather than from UCSC, so that row rests on "
              "a different alignment and species set from the two beside it, we recomputed "
              "conservation discrimination from phyloP queried at each variant position. **All four "
              "scores below are evaluated on exactly the same variants** (the intersection of the "
              "8,192-bp-scored, GERP-scorable and phyloP-scorable sets; cattle n = 1,921), "
              "so every comparison is like-for-like. Two things follow. First, phyloP is a **stronger** "
              # Methods review finding 6: a weaker comparator makes the model's margin larger, so GERP
              # being the weaker of the two makes every Evo 2-versus-conservation margin an UPPER
              # bound, not a conservative one. The old sentence had the inference backwards and the
              # same error stood in the Methods.
              "baseline than GERP in all three species, so every Evo 2-versus-conservation margin "
              "reported against GERP is an upper bound rather than a conservative one; GERP is kept "
              "as the primary comparator for uniformity across all nine assemblies, not for strength. "
              "Second, "
              "and more important, Evo 2 at the reference-implementation 8,192-bp readout beats even phyloP in "
              "all three, so the readout head-to-head (Table S12) is robust to using the stronger "
              "baseline; at the 1,001-bp readout, by contrast, phyloP beats Evo 2 in two of three, "
              "reinforcing that the single-position readout understates the model.\n")
            W("| Species | n (matched) | GERP | phyloP | phyloP − GERP | Evo 2 @8,192 | Evo 2 @8,192 − phyloP | Evo 2 @1,001 | Evo 2 @1,001 − phyloP |")
            W("|---|--:|--:|--:|--:|--:|--:|--:|--:|")
            for sp, r in rows:
                W("| %s | %s | %s | %s | %s | %s | %s | %s | %s |" % (
                    sp.capitalize(), r["n_matched"], f(r["auroc_gerp"]), f(r["auroc_phylop"]),
                    f(r["delta_phylop_minus_gerp"], 3, True), f(r["auroc_evo2_8192"]),
                    f(r["delta_evo2_8192_minus_phylop"], 3, True), f(r["auroc_evo2_1001"]),
                    f(r["delta_evo2_1001_minus_phylop"], 3, True)))
            W("\nphyloP was queried with pybigtools from genuine bigWig tracks (`build_phylop_crosscheck.py`); "
              "chromosome coordinates were mapped through the UCSC chromAlias, and no positive variant was "
              "dropped for want of a coordinate in any species.")

    # ---- Tables S25-S28: the controls added in response to the expert reviews ----------------
    # Each is generated from its deposited JSON, like everything above it, so the supplement cannot
    # drift from the analysis.

    if os.path.exists(R + "omia_trait_sensitivity.json"):
        d = J("omia_trait_sensitivity")
        W("\n## Table S25. OMIA trait alleles: which positives are not disease variants, and what "
          "removing them does\n")
        W("OMIA catalogues single-gene traits and disorders together, so some positives are trait "
          "alleles: coat and feather colour and type, production traits, blood groups, gait and "
          "resistance to infection. Each positive's class is curated from its OMIA phenotype string "
          "(Additional file 3: tables/atlas_positive_annotations.parquet and the rules in its builder). "
          "Removing the trait alleles and rescoring the identical panel at the identical 8,192-bp "
          "readout raises discrimination in every species that keeps at least five disease alleles, "
          "so their presence works against the reported result rather than for it, and the figures "
          "we report throughout are the full-panel ones. A species keeping fewer than five disease "
          "alleles has no disease-only AUROC. Built by `src/ccs/omia_trait_sensitivity.py`.\n")
        W("| Species | n | positives | trait positives | AUROC (full panel) | AUROC (disease only) | Δ |")
        W("|---|--:|--:|--:|--:|--:|--:|")
        for r in d["per_species"]:
            W("| %s | %d | %d | %d | %s | %s | %s |" % (
                r["species"].capitalize(), r["n"], r["pos"], r["trait_pos"],
                f(r["auroc_all"]), f(r["auroc_disease"]), f(r["delta"], 4, True)))
        W("| **Mean, %d species** | | %d | %d | %s | %s | %s |" % (
            d.get("n_species_estimable", 9), d["positives_total"], d["trait_positives_removed"],
            f(d.get("macro_all_estimable", d["macro_all"])), f(d["macro_disease"]),
            f(d["macro_disease"] - d.get("macro_all_estimable", d["macro_all"]), 4, True)))
        # Report the non-human denominator alongside the full one. Human contributes 1,500
        # ClinVar positives that cannot be trait alleles, because OMIA excludes human, so the
        # 3.7% figure understates the share in the panels that can actually carry them.
        _nh = [r for r in d["per_species"] if r["species"] != "human"]
        _nhp = sum(r["pos"] for r in _nh)
        _nht = sum(r["trait_pos"] for r in _nh)
        _worst = max(_nh, key=lambda r: (r["trait_pos"] / r["pos"]) if r["pos"] else 0.0)
        W("\nTrait positives removed: %d of %d (%.1f%%), or %d of %d (%.1f%%) across the eight "
          "OMIA species, and %d of %d (%.0f%%) in %s at the maximum. Pooled AUROC moves %s to %s."
          % (d["trait_positives_removed"], d["positives_total"],
             100.0 * d["trait_positives_removed"] / d["positives_total"],
             _nht, _nhp, 100.0 * _nht / _nhp,
             _worst["trait_pos"], _worst["pos"],
             100.0 * _worst["trait_pos"] / _worst["pos"], _worst["species"],
             f(d["pooled_all"]), f(d["pooled_disease"])))

    if os.path.exists(R + "gerp_consequence.json"):
        g = J("gerp_consequence")
        ev = J("fig3_consequence")["classes"]
        W("\n## Table S26. The consequence gradient is not the model's alone: GERP through the "
          "identical analysis\n")
        # This said "the same positives, the same per-species negatives". It is
        # not: GERP is defined only where its track returns a finite value, so the GERP arm runs on
        # different positives in all four classes (110/67/310/21 against Evo 2's 112/70/324/18), a
        # different species set (cattle enters every GERP class and carries none in the Evo 2 arm;
        # goat leaves nonsense) and a strictly smaller negative pool. The difference column therefore
        # differences two AUROCs on non-nested sets, which is the reach mismatch this paper exists to
        # quantify, arising inside our own control.
        W("The same positive-count-weighted estimator as the Evo 2 gradient, with GERP in place of "
          "Evo 2 — but **not the same variants, and we state that rather than let the table imply "
          "it.** GERP is defined only where its track returns a finite value, so this arm runs on the "
          "GERP-reachable subset: different positive counts in all four classes (nonsense 110 against "
          "Evo 2's 112, splicing 67 against 70, missense 310 against 324, regulatory 21 against 18), "
          "a different species set (cattle enters every GERP class and carries none in the Evo 2 arm; "
          "goat leaves the nonsense class), and a strictly smaller negative pool. The "
          "\"Evo 2 − GERP\" column therefore differences two AUROCs computed on non-nested sets, "
          "the same reach mismatch Table S7 and Note S28 quantify, arising here inside our own "
          "control. Read the two columns as two gradients of the same shape rather than as a "
          "difference: conservation also reaches its floor on the regulatory class, so the gradient "
          "reflects a constraint structure both scores inherit rather than a decay peculiar to the "
          "model. The regulatory cell rests on 21 GERP-reachable positives against 18 unmatched ones "
          "and is the least well powered of the four. Built by `src/ccs/gerp_consequence.py`.\n")
        W("| Consequence class | n positives (GERP-scorable) | Evo 2 | GERP | Evo 2 − GERP |")
        W("|---|--:|--:|--:|--:|")
        for c, r in g["classes"].items():
            e = ev.get(c, {}).get("auroc")
            W("| %s | %d | %s | %s | %s |" % (
                c, r["n_pos"], f(e), f(r["auroc_gerp"]),
                f(e - r["auroc_gerp"], 3, True) if e is not None else "--"))

    if os.path.exists(R + "clinvar_benign_arm.json"):
        b = J("clinvar_benign_arm")
        W("\n## Table S27. How much the human figure depends on which benign variants are drawn\n")
        W("The human arm's 1,500 negatives are a matched sample from ClinVar's benign half; every one "
          "of them is a Benign/Likely_benign record, so human is the one species whose negatives are "
          "clinically adjudicated rather than catalogued population variation. This rescores the same "
          "1,500 positives against a larger and differently composed sample of the same catalogue, at "
          "the identical 1,001-bp readout on GRCh38. Both draws are ClinVar B/LB, so what this bounds "
          "is sampling and composition sensitivity, not the population-versus-adjudicated question, "
          "which the human arm cannot pose. Built by `src/ccs/clinvar_benign_arm.py`.\n")
        W("| Negative set | n negatives | AUROC | 95% CI |")
        W("|---|--:|--:|:--|")
        rowspec = [("ClinVar B/LB, all", "all"),
                   ("ClinVar B/LB, coding only", "coding_negatives"),
                   ("ClinVar B/LB, noncoding only", "noncoding_negatives")]
        for label, key in rowspec:
            r = b.get(key)
            if not r:
                continue
            W("| %s | %d | %s | %s |" % (label, r["n_neg"], f(r["auroc"]),
                                         ci(r["ci95"][0], r["ci95"][1])))
        W("\nAgainst the atlas panel's own 1,500 benign negatives the same positives give 0.825, so "
          "the human figure moves by −0.014 (coding-only) to +0.040 (noncoding-only) with the benign "
          "draw; the range is asymmetric, the noncoding draw is the larger move, and it is not a "
          "±0.03 band, within a "
          "single catalogue.")

    if os.path.exists(R + "evidence_strength.json"):
        e = J("evidence_strength")
        W("\n## %s\n" % CAPTION_S28)
        W(NOTE_S28 + " Built by `src/ccs/evidence_strength.py`.\n")
        W("| Benign-set quantile | score threshold | sensitivity | false-positive rate | LR+ | 95% CI |")
        W("|---|--:|--:|--:|--:|:--|")
        for r in e["sweep"]:
            W("| %s | %s | %s | %s | %.1f | %s |" % (
                r["benign_quantile"], f(r["threshold"], 2), f(r["sensitivity"]),
                f(r["fpr"], 4), r["lr_plus"],
                "[%.1f, %.1f]" % tuple(r["lr_plus_ci95"])))
        W("\n" + TAIL_S28)

    io.open(R + "supplementary_tables.md", "w", encoding="utf-8", newline="\n").write(
        "\n".join(out) + "\n")
    print("wrote reports/supplementary_tables.md (%d lines)" % len(out))


if __name__ == "__main__":
    main()
