# -*- coding: utf-8 -*-
"""Assemble reports/gb_supplementary.md, Additional file 1, from its two generated halves.

build_supplementary.py mentions this script in its docstring, but it did not exist. The consequence
was that reports/gb_supplementary.md, which the submission renderer turns into the
Additional file 1 .docx that actually gets submitted, was a stale hand-edited artefact carrying two
tables while supplementary_tables.md carried fifteen. Every regeneration of the tables silently
failed to reach the submitted document.

    python src/ccs/build_supplementary.py
    python src/ccs/build_supplementary_extra.py
    python src/ccs/build_supplementary_doc.py
"""
import io
import re
import sys

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

PROSE = "reports/supplementary_prose.md"
TABLES = "reports/supplementary_tables.md"
OUT = "reports/gb_supplementary.md"


def main():
    prose = io.open(PROSE, encoding="utf-8").read().strip()
    tables = io.open(TABLES, encoding="utf-8").read().strip()

    # Additional file 1 shipped carrying the SUPERSEDED manuscript title on its own
    # header line, so an editor comparing the two files saw two differently-named papers. The title
    # lives in two places and nothing tied them together; this does.
    import re as _re
    _ms = io.open("reports/manuscript.md", encoding="utf-8").read()
    _title = _re.search(r"(?m)^#\s+(.*)$", _ms).group(1).strip()
    _head = _re.search(r"(?m)^\*\*(.+)\*\*\s*$", prose)
    if not _head or _head.group(1).strip() != _title:
        sys.exit("supplement title does not match the manuscript H1.\n"
                 "  manuscript: %s\n  supplement: %s\n"
                 "Fix the header line in %s." % (_title,
                                                 _head.group(1).strip() if _head else "(none found)",
                                                 PROSE))

    # supplementary_tables.md carries its own "# Supplementary Tables" banner plus a do-not-edit
    # note aimed at whoever maintains the repository; neither belongs in a submitted document.
    tables = re.sub(r"^# Supplementary Tables\s*\n+\*Generated by[^\n]*\n", "", tables, count=1, flags=re.M)

    body = prose + "\n\n---\n\n# Supplementary Tables\n\n" + tables + "\n"

    # Additional file 1 used ~20 distinct bracketed citation numbers and
    # carried no reference list of its own, so a reader of that file alone could resolve none of
    # them. Generated from the manuscript's list rather than maintained by hand, and numbered with
    # it, so the two cannot drift and no renumbering pass has to remember this file.
    refs = {}
    for m in re.finditer(r"(?m)^(\d+)\.\s+(.+)$", _ms[_ms.rindex("\n1. Nguyen"):]):
        refs[int(m.group(1))] = m.group(2).strip()
    cited = set()
    for m in re.finditer(r"\[(\d+(?:\s*[-–]\s*\d+)?(?:\s*,\s*\d+(?:\s*[-–]\s*\d+)?)*)\]", body):
        for part in m.group(1).split(","):
            part = part.strip()
            rng = re.match(r"^(\d+)\s*[-–]\s*(\d+)$", part)
            if rng:
                cited.update(range(int(rng.group(1)), int(rng.group(2)) + 1))
            elif part.isdigit():
                cited.add(int(part))
    missing = sorted(n for n in cited if n not in refs)
    if missing:
        sys.exit("supplement cites references absent from the manuscript list: %s" % missing)
    if cited:
        body += ("\n---\n\n# References\n\nNumbering follows the main manuscript. Only the references "
                 "cited in this file are listed.\n\n"
                 + "\n\n".join("%d. %s" % (n, refs[n]) for n in sorted(cited)) + "\n")

    io.open(OUT, "w", encoding="utf-8", newline="\n").write(body)

    n_tab = len(re.findall(r"^## Table S\d+", body, re.M))
    n_note = len(re.findall(r"^## Note S\d+", body, re.M))
    n_fig = len(re.findall(r"^## Figure S\d+", body, re.M))
    print("wrote %s: %d notes, %d tables, %d figure legends, %s words"
          % (OUT, n_note, n_tab, n_fig, format(len(body.split()), ",")))

    # A citation in the manuscript pointing at a table this file does not contain is exactly the
    # failure this script exists to prevent, so check it here rather than trusting the build.
    ms = io.open("reports/manuscript.md", encoding="utf-8").read()
    cited = set(re.findall(r"Table S(\d+)", ms)) | set(re.findall(r"Figure S(\d+)", ms))
    have = set(re.findall(r"^## Table S(\d+)", body, re.M)) | set(re.findall(r"^## Figure S(\d+)", body, re.M))
    missing = sorted(cited - have, key=int)
    if missing:
        print("  *** CITED BUT ABSENT: %s ***" % ", ".join("S" + m for m in missing))
        return 1
    print("  every cited supplementary item is present")
    return 0


if __name__ == "__main__":
    sys.exit(main())
