#!/usr/bin/env python3
"""Export the submitted DOCX files to the Markdown surfaces the deposited gates read.

    python tools/export_from_submission.py 01_Manuscript_GigaScience_v2.0.docx 12_Additional_file_1_Supplementary_v1.1.docx

Writes, under reports/:
    supplementary_prose.md    the whole of Additional file 1
    supplementary_tables.md   its numbered tables alone
    manuscript.md             the manuscript (only if the manuscript DOCX is given)

Why this exists. The submitted documents are the single authority for their own text.
Shipping a second copy of that text inside the code deposit guarantees the two will
diverge, so `reports/manuscript.md` is deliberately NOT deposited (see the DROP
list in tools/build_code_zip.py) and the two supplementary Markdown files are deposited
only as an export of the submitted document, regenerated by this script.

Consequently `tools/manuscript/scripts/consistency_check.py` and
`src/ccs/build_supplementary_doc.py`, which read `reports/manuscript.md`, are
runnable from the deposit only after this script has been run against the submitted
files. Every other gate runs from the deposit alone.

This is an EXPORT, not a rebuild. It transcribes the submitted documents and re-derives
nothing. `tools/check_traceability.py` and `tools/verify_from_data.py` are the checks
that re-derive published values from artefacts and from raw data respectively.
"""
import os, re, sys, zipfile

W = "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}"


def _blocks(path):
    """Yield ('p', style, text) and ('tbl', None, rows) in document order."""
    from xml.etree import ElementTree as ET
    body = ET.fromstring(zipfile.ZipFile(path).read("word/document.xml")).find(W + "body")

    def text(el):
        """Concatenate run text, marking bold runs with ** so the Markdown keeps the
        emphasis the submitted document carries. Gates such as the `table1` section of
        tools/verify_from_data.py locate rows by their bold labels."""
        out = []
        for r in el.iter(W + "r"):
            s = "".join(t.text or "" for t in r.iter(W + "t"))
            if not s:
                continue
            b = r.find(W + "rPr/" + W + "b")
            bold = b is not None and b.get(W + "val") not in ("0", "false")
            out.append("**" + s + "**" if bold and s.strip() else s)
        return "".join(out).replace("****", "")
    for el in body:
        if el.tag == W + "p":
            st = el.find(W + "pPr/" + W + "pStyle")
            yield "p", (st.get(W + "val") if st is not None else None), text(el)
        elif el.tag == W + "tbl":
            yield "tbl", None, [[text(tc) for tc in tr.findall(W + "tc")]
                                for tr in el.findall(W + "tr")]


def _md_table(rows):
    if not rows:
        return []
    n = max(len(r) for r in rows)
    rows = [r + [""] * (n - len(r)) for r in rows]
    esc = lambda c: c.replace("|", "\\|").strip()
    # Markdown renders the header row bold already, and the deposited gates locate the
    # header by its plain text, so header emphasis is dropped rather than doubled.
    hdr = lambda c: esc(c).replace("**", "")
    return (["| " + " | ".join(hdr(c) for c in rows[0]) + " |", "|" + "---|" * n]
            + ["| " + " | ".join(esc(c) for c in r) + " |" for r in rows[1:]])


def _write(name, lines):
    os.makedirs("reports", exist_ok=True)
    txt = re.sub(r"\n{3,}", "\n\n", "\n".join(lines)).strip() + "\n"
    n_note = len({int(m) for m in re.findall(r"## Note S(\d+)\.", txt)})
    n_tab = len({int(m) for m in re.findall(r"## Table S(\d+)\.", txt)})
    shape = f"{len(txt.splitlines())} lines, {n_note} notes, {n_tab} tables"

    # The deposit ships reports/*.md read-only on purpose, so a stale artefact fails loudly
    # instead of being silently overwritten (docs/REPRODUCING.md). The deposited exports are
    # already generated from the submitted documents, so the common case is that there is
    # nothing to write: say so and touch nothing.
    if os.path.exists(name):
        with open(name, encoding="utf-8") as fh:
            if fh.read() == txt:
                print(f"unchanged {name}: {shape} (already matches the submitted document)")
                return
    try:
        open(name, "w", encoding="utf-8", newline="\n").write(txt)
    except PermissionError:
        print(f"CANNOT WRITE {name}: it is deposited read-only and its content differs from the "
              f"submitted document.")
        print(f"  This is the archive's stale-artefact guard, not a bug. To regenerate it:")
        print(f"      chmod u+w {name} && python tools/export_from_submission.py <docx> ...")
        raise SystemExit(4)
    print(f"wrote {name}: {shape}")


def export_supplement(src):
    blocks = list(_blocks(src))
    start = next(i for i, (k, st, t) in enumerate(blocks)
                 if k == "p" and st == "Heading1" and t.strip().startswith("Additional file 1"))
    prose = ["# Supplementary information, exported from the submitted Additional file 1", "",
             "Generated by `tools/export_from_submission.py`. This file transcribes the submitted "
             "document; it re-derives nothing.", ""]
    tables = ["# Supplementary tables, exported from the submitted Additional file 1", ""]
    # A numbered table starts at its title, "Table S<n>. ...", set either as a Heading 2 or as a Caption
    # paragraph directly above the table body. Its notes are the paragraphs after the body up to the next
    # heading or title; a table printed inside a note (Table S34) keeps only its "Table S<n> notes."
    # paragraph, because the prose after it belongs to the note.
    cur, in_tables_section, table_body_seen = None, False, False
    for kind, style, payload in blocks[start:]:
        if kind == "p":
            t = payload.strip()
            if not t:
                continue
            plain = t.replace("**", "")
            is_title = bool(re.match(r"^Table S\d+\.", plain)) and style in ("Heading2", "Caption")
            if style == "Heading1":
                prose += ["", "# " + t, ""]; cur = None
                in_tables_section = plain.startswith("Supplementary Tables")
            elif style == "Heading2":
                prose += ["", "## " + t, ""]
                cur = "table" if is_title else "note"
                table_body_seen = False
                if cur == "table":
                    tables += ["", "## " + plain, ""]
            elif is_title:
                prose.append(t)
                cur, table_body_seen = "table", False
                tables += ["", "## " + plain, ""]
            else:
                prose.append(t)
                if cur == "table":
                    if not table_body_seen or in_tables_section or re.match(r"^Table S\d+ notes", plain):
                        tables.append(t)
                    else:
                        cur = "note"
        else:
            md = _md_table(payload)
            prose += [""] + md + [""]
            if cur == "table":
                tables += [""] + md + [""]
                table_body_seen = True
    _write("reports/supplementary_prose.md", prose)
    # Refuse to write a tables file with no tables in it. A table section starts only at a
    # "Table S<n>." title in a heading or caption style, so a supplement whose titles carry some other
    # style would yield a 1-line, 0-table file, written over the deposited export at exit 0. The
    # archive ships reports/ read-only, which stops that too, but a tool must not depend on a file
    # permission to avoid destroying its own output.
    if not any(re.match(r"## Table S\d+\.", ln) for ln in tables):
        name = "reports/supplementary_tables.md"
        have = (len(set(re.findall(r"^## Table S(\d+)\.", open(name, encoding="utf-8").read(), re.M)))
                if os.path.exists(name) else 0)
        print("REFUSING to write %s: extracted 0 tables." % name)
        print("  The deposited file has %d. No paragraph of the submitted .docx opened a table" % have)
        print("  section (a 'Table S<n>.' title in a Heading 2 or Caption style), so writing would")
        print("  replace a complete export with an empty one. The prose export above was written.")
        return 4
    _write("reports/supplementary_tables.md", tables)


def export_manuscript(src):
    out = ["# Manuscript, exported from the submitted manuscript DOCX", "",
           "Generated by `tools/export_from_submission.py`; not deposited, because the submitted "
           "DOCX is the authority for its own text.", ""]
    for kind, style, payload in _blocks(src):
        if kind == "p":
            t = payload.strip()
            if not t:
                continue
            if style == "Heading1":   out += ["", "# " + t, ""]
            elif style == "Heading2": out += ["", "## " + t, ""]
            elif style == "Heading3": out += ["", "### " + t, ""]
            else:                     out.append(t)
        else:
            out += [""] + _md_table(payload) + [""]
    _write("reports/manuscript.md", out)


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("-")]
    if not args:
        sys.exit(__doc__)
    for a in args:
        if not os.path.exists(a):
            sys.exit("not found: " + a)
    # Propagate the refusal. export_supplement() returns 4 when it declines to overwrite a
    # complete export with an empty one, but that value used to be discarded here, so the tool
    # printed "REFUSING" and exited 0 -- a message contradicting its own exit code, which any
    # calling script reads as success.
    rc = 0
    for a in args:
        blocks = list(_blocks(a))
        is_supp = any(k == "p" and st == "Heading1"
                      and t.strip().startswith("Additional file 1")
                      for k, st, t in blocks)
        rc = (export_supplement if is_supp else export_manuscript)(a) or rc
    return rc


if __name__ == "__main__":
    sys.exit(main())
